version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
       - ./redis/init_redis.sh:/app/init_redis.sh
    ports:
      - 6379:6379

  exporter:
    build: ./exporter/
    restart: always
    ports:
      - 8000:8000
    env_file: ./exporter/settings.env
